retryable_workflows:
  - "test"
  - "Tests"
  - "benchmark"
  - "Benchmark"
retryable_step_names:
  - "Install PyTorch"
  - "Install Triton from source"
  - "CUDA Compute Check"
  - "Inductor Worker Check"
  - "XPU Compute Check"
