"""Measured SM103 configs, keyed by exact public kernel signatures. No runtime I/O."""
from __future__ import annotations
import helion
import torch

STRUCTURAL_POLICY = helion.CuteStructuralPolicy(cute_region_fission=True, cute_full_slice_matmul_tiling=True, cute_segmented_matmul_tiling=True, cute_flatten_nested_reductions=True, cute_materialize_transformed_operands=True)

def _signature(args):
    def part(value):
        if isinstance(value, torch.Tensor):
            return str(value.dtype), tuple(value.shape), tuple(value.stride())
        if isinstance(value, torch.dtype):
            return str(value)
        if value is None or isinstance(value, (bool, int, float, str)):
            return value
        raise TypeError(f"Unsupported argument: {type(value).__name__}")
    return tuple(part(value) for value in args)

_CATEGORICAL_CONFIGS = {(('torch.float32', (16449536,), (1,)), ('torch.int64', (1,), (1,)), 128512, False, 'torch.int32'): {'block_sizes': [4,
                                                                                                                     256,
                                                                                                                     4],
                                                                                                     'cute_cluster_n': 16,
                                                                                                     'cute_fragment_reduction': 'warp',
                                                                                                     'cute_fragment_scan': 'cooperative',
                                                                                                     'cute_fragment_threads': 512,
                                                                                                     'cute_independent_reduction': False,
                                                                                                     'cute_lane_layouts': ['blocked',
                                                                                                                           'strided',
                                                                                                                           'strided',
                                                                                                                           'blocked'],
                                                                                                     'cute_min_blocks_per_mp': 1,
                                                                                                     'cute_reduction_reloads': ['gmem'],
                                                                                                     'cute_replicated_reduction': False,
                                                                                                     'cute_vector_packet_unroll': False,
                                                                                                     'cute_vector_widths': [4,
                                                                                                                            2,
                                                                                                                            1,
                                                                                                                            4],
                                                                                                     'load_eviction_policies': ['first',
                                                                                                                                'l1_l2_first',
                                                                                                                                'l2_last',
                                                                                                                                '',
                                                                                                                                '',
                                                                                                                                '',
                                                                                                                                'l1_l2_first',
                                                                                                                                'streaming',
                                                                                                                                'streaming'],
                                                                                                     'loop_orders': [[1,
                                                                                                                      0]],
                                                                                                     'num_threads': [4,
                                                                                                                     32,
                                                                                                                     0,
                                                                                                                     0]},
 (('torch.float32', (32899072,), (1,)), ('torch.int64', (1,), (1,)), 128512, True, 'torch.int32'): {'block_sizes': [8,
                                                                                                                    512,
                                                                                                                    1],
                                                                                                    'cute_cluster_n': 4,
                                                                                                    'cute_fragment_reduction': 'warp',
                                                                                                    'cute_fragment_scan': 'cooperative',
                                                                                                    'cute_fragment_threads': 256,
                                                                                                    'cute_independent_reduction': False,
                                                                                                    'cute_lane_layouts': ['blocked',
                                                                                                                          'blocked',
                                                                                                                          'strided',
                                                                                                                          'strided'],
                                                                                                    'cute_min_blocks_per_mp': 1,
                                                                                                    'cute_reduction_reloads': ['gmem'],
                                                                                                    'cute_replicated_reduction': False,
                                                                                                    'cute_vector_packet_unroll': False,
                                                                                                    'cute_vector_widths': [4,
                                                                                                                           2,
                                                                                                                           1,
                                                                                                                           1],
                                                                                                    'load_eviction_policies': ['first',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'streaming',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'first',
                                                                                                                               'streaming',
                                                                                                                               'first',
                                                                                                                               'first'],
                                                                                                    'loop_orders': [[1,
                                                                                                                     0]],
                                                                                                    'num_threads': [0,
                                                                                                                    16,
                                                                                                                    0,
                                                                                                                    0]},
 (('torch.float32', (4112384,), (1,)), ('torch.int64', (1,), (1,)), 128512, False, 'torch.int32'): {'block_sizes': [2,
                                                                                                                    256,
                                                                                                                    1],
                                                                                                    'cute_cluster_n': 8,
                                                                                                    'cute_fragment_reduction': 'warp',
                                                                                                    'cute_fragment_scan': 'cooperative',
                                                                                                    'cute_independent_reduction': False,
                                                                                                    'cute_lane_layouts': ['blocked',
                                                                                                                          'strided',
                                                                                                                          'strided',
                                                                                                                          'blocked'],
                                                                                                    'cute_min_blocks_per_mp': 1,
                                                                                                    'cute_reduction_reloads': ['auto'],
                                                                                                    'cute_replicated_reduction': False,
                                                                                                    'cute_vector_packet_unroll': False,
                                                                                                    'cute_vector_widths': [2,
                                                                                                                           8,
                                                                                                                           8,
                                                                                                                           8],
                                                                                                    'load_eviction_policies': ['',
                                                                                                                               'l1_l2_first',
                                                                                                                               'l2_last',
                                                                                                                               'l2_last',
                                                                                                                               'l1_l2_first',
                                                                                                                               'l2_last',
                                                                                                                               '',
                                                                                                                               'last',
                                                                                                                               'l1_l2_last'],
                                                                                                    'loop_orders': [[0,
                                                                                                                     1]],
                                                                                                    'num_threads': [2,
                                                                                                                    64,
                                                                                                                    1,
                                                                                                                    1024]},
 (('torch.float32', (65798144,), (1,)), ('torch.int64', (1,), (1,)), 128512, False, 'torch.int32'): {'block_sizes': [16,
                                                                                                                     512,
                                                                                                                     16],
                                                                                                     'cute_cluster_n': 1,
                                                                                                     'cute_fragment_reduction': 'warp',
                                                                                                     'cute_fragment_scan': 'cooperative',
                                                                                                     'cute_fragment_threads': 512,
                                                                                                     'cute_independent_reduction': False,
                                                                                                     'cute_lane_layouts': ['blocked',
                                                                                                                           'blocked',
                                                                                                                           'strided',
                                                                                                                           'blocked'],
                                                                                                     'cute_min_blocks_per_mp': 0,
                                                                                                     'cute_reduction_reloads': ['register'],
                                                                                                     'cute_replicated_reduction': False,
                                                                                                     'cute_vector_packet_unroll': False,
                                                                                                     'cute_vector_widths': [4,
                                                                                                                            8,
                                                                                                                            1,
                                                                                                                            1],
                                                                                                     'load_eviction_policies': ['streaming',
                                                                                                                                'last',
                                                                                                                                'l1_l2_last',
                                                                                                                                'l1_l2_last',
                                                                                                                                '',
                                                                                                                                'first',
                                                                                                                                'streaming',
                                                                                                                                'streaming',
                                                                                                                                'last'],
                                                                                                     'loop_orders': [[1,
                                                                                                                      0]],
                                                                                                     'num_threads': [0,
                                                                                                                     32,
                                                                                                                     16,
                                                                                                                     0]},
 (('torch.float32', (8224768,), (1,)), ('torch.int64', (1,), (1,)), 128512, True, 'torch.int32'): {'block_sizes': [4,
                                                                                                                   128,
                                                                                                                   1],
                                                                                                   'cute_cluster_n': 1,
                                                                                                   'cute_fragment_reduction': 'warp',
                                                                                                   'cute_fragment_scan': 'cooperative',
                                                                                                   'cute_fragment_threads': 512,
                                                                                                   'cute_independent_reduction': False,
                                                                                                   'cute_lane_layouts': ['blocked',
                                                                                                                         'blocked',
                                                                                                                         'blocked',
                                                                                                                         'blocked'],
                                                                                                   'cute_min_blocks_per_mp': 0,
                                                                                                   'cute_reduction_reloads': ['auto'],
                                                                                                   'cute_replicated_reduction': False,
                                                                                                   'cute_vector_packet_unroll': False,
                                                                                                   'cute_vector_widths': [2,
                                                                                                                          1,
                                                                                                                          1,
                                                                                                                          1],
                                                                                                   'load_eviction_policies': ['l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              '',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last',
                                                                                                                              'streaming',
                                                                                                                              'l2_last',
                                                                                                                              'l2_last'],
                                                                                                   'loop_orders': [[1,
                                                                                                                    0]],
                                                                                                   'num_threads': [1,
                                                                                                                   0,
                                                                                                                   0,
                                                                                                                   0]}}

def key_categorical(*args):
    key = _signature(args)
    if key not in _CATEGORICAL_CONFIGS:
        raise ValueError(f"No measured categorical config for {key}")
    return key

def autotune_categorical(*args):
    return helion.CuteStructuralConfig(_CATEGORICAL_CONFIGS[key_categorical(*args)], STRUCTURAL_POLICY)

_CATEGORICAL_GUMBEL_CONFIGS = {(('torch.float32', (99, 32000), (32000, 1)), ('torch.int64', (1,), (1,)), ('torch.float32', (99,), (1,)), False, True, 'torch.int32'): {'block_sizes': [1,
                                                                                                                                                         1024],
                                                                                                                                         'cute_cluster_n': 1,
                                                                                                                                         'cute_independent_reduction': False,
                                                                                                                                         'cute_integer_loop_reduction': True,
                                                                                                                                         'cute_lane_layouts': ['blocked',
                                                                                                                                                               'strided'],
                                                                                                                                         'cute_min_blocks_per_mp': 4,
                                                                                                                                         'cute_reduction_sequence': 'bounded_layout',
                                                                                                                                         'cute_replicated_reduction': False,
                                                                                                                                         'cute_vector_packet_unroll': False,
                                                                                                                                         'cute_vector_widths': [2,
                                                                                                                                                                8],
                                                                                                                                         'load_eviction_policies': ['first',
                                                                                                                                                                    'first',
                                                                                                                                                                    'l2_last',
                                                                                                                                                                    'first',
                                                                                                                                                                    'first',
                                                                                                                                                                    'first',
                                                                                                                                                                    'first',
                                                                                                                                                                    'l2_last',
                                                                                                                                                                    'first',
                                                                                                                                                                    'first'],
                                                                                                                                         'num_threads': [1,
                                                                                                                                                         0]}}

def key_categorical_gumbel(*args):
    key = _signature(args)
    if key not in _CATEGORICAL_GUMBEL_CONFIGS:
        raise ValueError(f"No measured categorical_gumbel config for {key}")
    return key

def autotune_categorical_gumbel(*args):
    return helion.CuteStructuralConfig(_CATEGORICAL_GUMBEL_CONFIGS[key_categorical_gumbel(*args)], STRUCTURAL_POLICY)

_CATEGORICAL_V2_CONFIGS = {(('torch.float32', (2056192,), (1,)), ('torch.int64', (1,), (1,)), 128512, True, 'torch.int32'): {'block_sizes': [16,
                                                                                                                   512,
                                                                                                                   1],
                                                                                                   'cute_cluster_n': 2,
                                                                                                   'cute_fragment_reduction': 'warp',
                                                                                                   'cute_independent_reduction': False,
                                                                                                   'cute_lane_layouts': ['blocked',
                                                                                                                         'strided',
                                                                                                                         'strided',
                                                                                                                         'strided'],
                                                                                                   'cute_min_blocks_per_mp': 3,
                                                                                                   'cute_reduction_reloads': ['register'],
                                                                                                   'cute_replicated_reduction': False,
                                                                                                   'cute_vector_packet_unroll': False,
                                                                                                   'cute_vector_widths': [2,
                                                                                                                          4,
                                                                                                                          1,
                                                                                                                          8],
                                                                                                   'load_eviction_policies': ['l1_l2_first',
                                                                                                                              '',
                                                                                                                              'streaming',
                                                                                                                              'l1_l2_first',
                                                                                                                              'l2_last',
                                                                                                                              '',
                                                                                                                              'first',
                                                                                                                              'l1_l2_last',
                                                                                                                              'last',
                                                                                                                              'streaming',
                                                                                                                              'l2_last',
                                                                                                                              'streaming',
                                                                                                                              'last'],
                                                                                                   'loop_orders': [[1,
                                                                                                                    0]],
                                                                                                   'num_threads': [0,
                                                                                                                   16,
                                                                                                                   1,
                                                                                                                   16]}}

def key_categorical_v2(*args):
    key = _signature(args)
    if key not in _CATEGORICAL_V2_CONFIGS:
        raise ValueError(f"No measured categorical_v2 config for {key}")
    return key

def autotune_categorical_v2(*args):
    return helion.CuteStructuralConfig(_CATEGORICAL_V2_CONFIGS[key_categorical_v2(*args)], STRUCTURAL_POLICY)

CONFIGS = [helion.CuteStructuralConfig(config, STRUCTURAL_POLICY) for configs in (_CATEGORICAL_CONFIGS.values(), _CATEGORICAL_GUMBEL_CONFIGS.values(), _CATEGORICAL_V2_CONFIGS.values(),) for config in configs]

_HELION_AOT_STRUCTURAL_MANIFEST = {"schema": "helion.aot.structural_model", "version": 1,"policy": STRUCTURAL_POLICY.to_dict(), "policy_id": STRUCTURAL_POLICY.identity(), "configs": {"categorical": [helion.CuteStructuralConfig(config, STRUCTURAL_POLICY).to_dict() for config in _CATEGORICAL_CONFIGS.values()], "categorical_gumbel": [helion.CuteStructuralConfig(config, STRUCTURAL_POLICY).to_dict() for config in _CATEGORICAL_GUMBEL_CONFIGS.values()], "categorical_v2": [helion.CuteStructuralConfig(config, STRUCTURAL_POLICY).to_dict() for config in _CATEGORICAL_V2_CONFIGS.values()]}}
