"""Exact GB300 AIR stage configurations for FP32[16, 128512], p=0.1.

These are a measured fixed-config diagnostic, not a cold-search winner.
Selection is pure metadata matching; unknown stage signatures are rejected.
"""

from __future__ import annotations

import json

import torch

import helion

POLICY = helion.CuteStructuralPolicy(
    cute_flatten_nested_reductions=False,
    cute_full_slice_matmul_tiling=False,
    cute_materialize_transformed_operands=False,
    cute_region_fission=False,
    cute_segmented_matmul_tiling=False,
)

_CONFIGS = {'histogram_0': {'block_sizes': [16, 32],
                 'cute_cluster_n': 1,
                 'cute_fragment_threads': 512,
                 'cute_independent_reduction': False,
                 'cute_lane_layouts': ['blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked'],
                 'cute_min_blocks_per_mp': 0,
                 'cute_replicated_reduction': False,
                 'cute_vector_packet_unroll': False,
                 'cute_vector_widths': [1, 1, 1, 1, 1, 1],
                 'load_eviction_policies': ['', '', '', '', ''],
                 'loop_orders': [[0, 1], [0, 1]]},
 'histogram_groups_0': {'block_sizes': [16, 32],
                        'cute_cluster_n': 1,
                        'cute_independent_reduction': False,
                        'cute_lane_layouts': ['blocked', 'blocked'],
                        'cute_min_blocks_per_mp': 0,
                        'cute_proven_bounds': False,
                        'cute_replicated_reduction': False,
                        'cute_vector_packet_unroll': False,
                        'cute_vector_widths': [1, 1],
                        'load_eviction_policies': ['',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   ''],
                        'loop_orders': [[0, 1]]},
 'choose_0': {'block_sizes': [16],
              'cute_cluster_n': 1,
              'cute_independent_reduction': False,
              'cute_lane_layouts': ['blocked', 'blocked', 'blocked'],
              'cute_min_blocks_per_mp': 0,
              'cute_replicated_reduction': False,
              'cute_vector_packet_unroll': False,
              'cute_vector_widths': [1, 1, 1],
              'load_eviction_policies': ['',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '',
                                         '']},
 'selected_count_0': {'block_sizes': [16],
                      'cute_cluster_n': 1,
                      'cute_independent_reduction': False,
                      'cute_lane_layouts': ['blocked'],
                      'cute_min_blocks_per_mp': 0,
                      'cute_proven_bounds': False,
                      'cute_replicated_reduction': False,
                      'cute_vector_packet_unroll': False,
                      'cute_vector_widths': [1],
                      'load_eviction_policies': ['', '']},
 'histogram_1': {'block_sizes': [16, 32],
                 'cute_cluster_n': 1,
                 'cute_fragment_scan': 'cooperative',
                 'cute_fragment_threads': 512,
                 'cute_independent_reduction': False,
                 'cute_lane_layouts': ['blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked'],
                 'cute_min_blocks_per_mp': 0,
                 'cute_reduction_reloads': ['auto'],
                 'cute_replicated_reduction': False,
                 'cute_vector_packet_unroll': False,
                 'cute_vector_widths': [1, 1, 1, 1, 1, 1, 1],
                 'load_eviction_policies': ['', '', '', '', '', '', '', '', '', '', ''],
                 'loop_orders': [[0, 1], [0, 1]]},
 'histogram_groups_1': {'block_sizes': [16, 32],
                        'cute_cluster_n': 1,
                        'cute_independent_reduction': False,
                        'cute_lane_layouts': ['blocked', 'blocked'],
                        'cute_min_blocks_per_mp': 0,
                        'cute_proven_bounds': False,
                        'cute_replicated_reduction': False,
                        'cute_vector_packet_unroll': False,
                        'cute_vector_widths': [1, 1],
                        'load_eviction_policies': ['',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   ''],
                        'loop_orders': [[0, 1]]},
 'choose_1': {'block_sizes': [16],
              'cute_cluster_n': 1,
              'cute_independent_reduction': False,
              'cute_lane_layouts': ['blocked', 'blocked', 'blocked'],
              'cute_min_blocks_per_mp': 0,
              'cute_replicated_reduction': False,
              'cute_vector_packet_unroll': False,
              'cute_vector_widths': [1, 1, 1],
              'load_eviction_policies': ['', '', '', '', '']},
 'selected_count_1': {'block_sizes': [16],
                      'cute_cluster_n': 1,
                      'cute_independent_reduction': False,
                      'cute_lane_layouts': ['blocked'],
                      'cute_min_blocks_per_mp': 0,
                      'cute_proven_bounds': False,
                      'cute_replicated_reduction': False,
                      'cute_vector_packet_unroll': False,
                      'cute_vector_widths': [1],
                      'load_eviction_policies': ['', '']},
 'histogram_2': {'block_sizes': [16, 32],
                 'cute_cluster_n': 1,
                 'cute_fragment_threads': 512,
                 'cute_independent_reduction': False,
                 'cute_lane_layouts': ['blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked',
                                       'blocked'],
                 'cute_min_blocks_per_mp': 0,
                 'cute_replicated_reduction': False,
                 'cute_vector_packet_unroll': False,
                 'cute_vector_widths': [1, 1, 1, 1, 1, 1],
                 'load_eviction_policies': ['',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            '',
                                            ''],
                 'loop_orders': [[0, 1], [0, 1]]},
 'histogram_groups_2': {'block_sizes': [16, 32],
                        'cute_cluster_n': 1,
                        'cute_independent_reduction': False,
                        'cute_lane_layouts': ['blocked', 'blocked'],
                        'cute_min_blocks_per_mp': 0,
                        'cute_proven_bounds': False,
                        'cute_replicated_reduction': False,
                        'cute_vector_packet_unroll': False,
                        'cute_vector_widths': [1, 1],
                        'load_eviction_policies': ['',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   '',
                                                   ''],
                        'loop_orders': [[0, 1]]},
 'choose_2': {'block_sizes': [16],
              'cute_cluster_n': 1,
              'cute_independent_reduction': False,
              'cute_lane_layouts': ['blocked', 'blocked', 'blocked'],
              'cute_min_blocks_per_mp': 0,
              'cute_replicated_reduction': False,
              'cute_vector_packet_unroll': False,
              'cute_vector_widths': [1, 1, 1],
              'load_eviction_policies': ['', '', '', '', '']},
 'apply_partials': {'block_sizes': [16, 32],
                    'cute_cluster_n': 1,
                    'cute_independent_reduction': False,
                    'cute_lane_layouts': ['blocked', 'blocked', 'blocked'],
                    'cute_min_blocks_per_mp': 0,
                    'cute_replicated_reduction': False,
                    'cute_vector_packet_unroll': False,
                    'cute_vector_widths': [1, 1, 1],
                    'load_eviction_policies': ['', '', '', ''],
                    'loop_orders': [[0, 1]]},
 'apply_groups': {'block_sizes': [16, 32],
                  'cute_cluster_n': 1,
                  'cute_independent_reduction': False,
                  'cute_lane_layouts': ['blocked', 'blocked'],
                  'cute_min_blocks_per_mp': 0,
                  'cute_proven_bounds': False,
                  'cute_replicated_reduction': False,
                  'cute_vector_packet_unroll': False,
                  'cute_vector_widths': [1, 1],
                  'load_eviction_policies': ['',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             '',
                                             ''],
                  'loop_orders': [[0, 1]]},
 'apply_output': {'block_sizes': [1, 256],
                  'cute_cluster_n': 1,
                  'cute_independent_reduction': False,
                  'cute_lane_layouts': ['blocked', 'blocked', 'blocked'],
                  'cute_min_blocks_per_mp': 0,
                  'cute_replicated_reduction': False,
                  'cute_vector_packet_unroll': False,
                  'cute_vector_widths': [1, 1, 1],
                  'load_eviction_policies': ['', '', '', ''],
                  'loop_orders': [[0, 1]]}}

_SIGNATURES = {'histogram_0': '[{"dtype":"torch.float32","shape":[16,128512],"stride":[128512,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16,4096],"stride":[4096,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},0,32]',
 'histogram_groups_0': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]}]',
 'choose_0': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.int32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.float32","shape":[16,64],"stride":[64,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16],"stride":[1]},0.1,0]',
 'selected_count_0': '[{"dtype":"torch.int32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},0]',
 'histogram_1': '[{"dtype":"torch.float32","shape":[16,128512],"stride":[128512,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16,4096],"stride":[4096,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},1,32]',
 'histogram_groups_1': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]}]',
 'choose_1': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.int32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.float32","shape":[16,64],"stride":[64,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16],"stride":[1]},0.1,1]',
 'selected_count_1': '[{"dtype":"torch.int32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},1]',
 'histogram_2': '[{"dtype":"torch.float32","shape":[16,128512],"stride":[128512,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16,4096],"stride":[4096,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},2,32]',
 'histogram_groups_2': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]}]',
 'choose_2': '[{"dtype":"torch.float32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.int32","shape":[16,2048],"stride":[2048,1]},{"dtype":"torch.float32","shape":[16,64],"stride":[64,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16],"stride":[1]},0.1,2]',
 'apply_partials': '[{"dtype":"torch.float32","shape":[16,128512],"stride":[128512,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]}]',
 'apply_groups': '[{"dtype":"torch.float32","shape":[16,1024],"stride":[1024,1]}]',
 'apply_output': '[{"dtype":"torch.float32","shape":[16,128512],"stride":[128512,1]},{"dtype":"torch.int32","shape":[16],"stride":[1]},{"dtype":"torch.float32","shape":[16,32],"stride":[32,1]}]'}

_STAGE_NAMES = {'histogram': ['histogram_0', 'histogram_1', 'histogram_2'],
 'histogram_groups': ['histogram_groups_0', 'histogram_groups_1', 'histogram_groups_2'],
 'choose': ['choose_0', 'choose_1', 'choose_2'],
 'selected_count': ['selected_count_0', 'selected_count_1'],
 'apply_partials': ['apply_partials'],
 'apply_groups': ['apply_groups'],
 'apply_output': ['apply_output']}
_CONFIGS_BY_SIGNATURE = {
    name: {_SIGNATURES[stage]: _CONFIGS[stage] for stage in stages}
    for name, stages in _STAGE_NAMES.items()
}
CONFIGS = [helion.CuteStructuralConfig(config, POLICY) for config in _CONFIGS.values()]
_HELION_AOT_STRUCTURAL_MANIFEST = {
    "schema": "helion.aot.structural_model",
    "version": 1,
    "policy": POLICY.to_dict(),
    "policy_id": POLICY.identity(),
    "configs": {
        name: [helion.CuteStructuralConfig(config, POLICY).to_dict()
               for config in configs.values()]
        for name, configs in _CONFIGS_BY_SIGNATURE.items()
    },
}


def _key(name: str, args: tuple[object, ...]) -> str:
    def describe(arg: object) -> object:
        if isinstance(arg, torch.Tensor):
            return {
                "shape": list(arg.shape),
                "stride": list(arg.stride()),
                "dtype": str(arg.dtype),
            }
        if arg is None or isinstance(arg, (bool, int, float, str)):
            return arg
        raise TypeError(f"Unsupported stage argument type: {type(arg).__name__}")

    signature = json.dumps(
        [describe(arg) for arg in args], sort_keys=True, separators=(",", ":")
    )
    if signature not in _CONFIGS_BY_SIGNATURE[name]:
        raise ValueError(f"No recorded AIR configuration for {name}: {signature}")
    return signature


def key_histogram(*args: object) -> str:
    return _key("histogram", args)


def autotune_histogram(*args: object) -> helion.CuteStructuralConfig:
    key = key_histogram(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["histogram"][key], POLICY)


def key_histogram_groups(*args: object) -> str:
    return _key("histogram_groups", args)


def autotune_histogram_groups(*args: object) -> helion.CuteStructuralConfig:
    key = key_histogram_groups(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["histogram_groups"][key], POLICY)


def key_choose(*args: object) -> str:
    return _key("choose", args)


def autotune_choose(*args: object) -> helion.CuteStructuralConfig:
    key = key_choose(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["choose"][key], POLICY)


def key_selected_count(*args: object) -> str:
    return _key("selected_count", args)


def autotune_selected_count(*args: object) -> helion.CuteStructuralConfig:
    key = key_selected_count(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["selected_count"][key], POLICY)


def key_apply_partials(*args: object) -> str:
    return _key("apply_partials", args)


def autotune_apply_partials(*args: object) -> helion.CuteStructuralConfig:
    key = key_apply_partials(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["apply_partials"][key], POLICY)


def key_apply_groups(*args: object) -> str:
    return _key("apply_groups", args)


def autotune_apply_groups(*args: object) -> helion.CuteStructuralConfig:
    key = key_apply_groups(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["apply_groups"][key], POLICY)


def key_apply_output(*args: object) -> str:
    return _key("apply_output", args)


def autotune_apply_output(*args: object) -> helion.CuteStructuralConfig:
    key = key_apply_output(*args)
    return helion.CuteStructuralConfig(_CONFIGS_BY_SIGNATURE["apply_output"][key], POLICY)
