"""Exact GB300/sm103 configs returned by twelve independent FULL searches.

These are per-workload AOT recipes, not a learned heuristic or compiler policy.
Inputs to each selector are the five flattened user-key scalars. Unsupported
shapes and dtypes are rejected rather than borrowing another workload's config.
The source kernel also checks CUDA capability, layout and Q/K/V agreement.
"""

from __future__ import annotations

from copy import deepcopy


_DENSE_KEYS = [(1, 8, 12288, 128, 'float16'),
 (2, 32, 16384, 128, 'float16'),
 (2, 32, 32768, 64, 'float16'),
 (2, 32, 2048, 64, 'float16'),
 (8, 32, 8192, 128, 'bfloat16'),
 (1, 1, 8192, 128, 'float16'),
 (2, 16, 8192, 128, 'float16'),
 (4, 32, 4096, 128, 'bfloat16')]

_DENSE_CONFIGS = [
    # case01: eba99c205cbf8ed0; FULL search seed 2026172201.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 72,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 2,
     'cute_flash_kv_order': 'descending',
     'cute_flash_kv_stage': 6,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 48,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': True,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 32,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'fa4',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 176,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case02: eaef17b4e5af6f2d; FULL search seed 2026172202.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 64,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 1,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 6,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 48,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': True,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 12.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'fa4',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 184,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
    # case03: 5709d41b7951347a; FULL search seed 2026220203.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 72,
     'cute_flash_corr_tile_size': 8,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 2,
     'cute_flash_e2e_offset0': 1,
     'cute_flash_e2e_schedule': '8/2',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': 'deg1_8x2_corr10',
     'cute_flash_first_load_order': 0,
     'cute_flash_kv_order': 'descending',
     'cute_flash_kv_stage': 6,
     'cute_flash_kv_tile_n': 160,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 40,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': True,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 8,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': True,
     'cute_flash_role_map': 'fa4',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'auto',
     'cute_flash_softmax_regs': 200,
     'cute_flash_softmax_setup': 'stage_local',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
    # case05: 8df30045e26d568b; FULL search seed 2026260205.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 4,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 2,
     'cute_flash_corr_regs': 72,
     'cute_flash_corr_tile_size': 32,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 4,
     'cute_flash_kv_order': 'descending',
     'cute_flash_kv_stage': 8,
     'cute_flash_kv_tile_n': 160,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 48,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': True,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_clc_local_tma',
     'cute_flash_precompute_qk_desc': True,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 8,
     'cute_flash_rescale_threshold': 12.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 184,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case07: 1fe8bac622ec2f94; FULL search seed 2026220207.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 80,
     'cute_flash_corr_tile_size': 8,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 2,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 4,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 80,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': True,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 8,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'fa4',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 176,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case08: 8b336d6f6767cce7; FULL search seed 2026210208.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 64,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': '16/8',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': False,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 0,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 2,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': False,
     'cute_flash_other_regs': 48,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'ws_overlap',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 1,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'software',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': True,
     'cute_flash_softmax_lowering': 'auto',
     'cute_flash_softmax_regs': 200,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'fragment',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'ring2',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
    # case09: 0ed0c82334cf554a; FULL search seed 2026220209.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 88,
     'cute_flash_corr_tile_size': 32,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 2,
     'cute_flash_kv_order': 'descending',
     'cute_flash_kv_stage': 6,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 56,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 12.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 184,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case11: f092788bbe9c9935; FULL search seed 2026220211.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'ascending',
     'cute_flash_causal_loop_split': False,
     'cute_flash_causal_lpt_swizzle': 0,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 88,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 0,
     'cute_flash_kv_order': 'descending',
     'cute_flash_kv_stage': 6,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 24,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': True,
     'cute_flash_persistent_ctas_per_sm': 2,
     'cute_flash_persistent_loop': 'counted',
     'cute_flash_pipeline_family': 'fa4_2cta',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 8,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_value_graph',
     'cute_flash_softmax_regs': 184,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
]


_CAUSAL_KEYS = [(2, 32, 65536, 64, 'float16'),
 (2, 32, 4096, 64, 'float16'),
 (1, 8, 12288, 128, 'float16'),
 (4, 32, 4096, 128, 'bfloat16')]

_CAUSAL_CONFIGS = [
    # case04: b660aa50ecc2e55b; FULL search seed 2026210204.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'descending',
     'cute_flash_causal_loop_split': True,
     'cute_flash_causal_lpt_swizzle': 2,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 64,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': False,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 0,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 4,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 32,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4',
     'cute_flash_precompute_qk_desc': True,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 4.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'pre_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_stateful',
     'cute_flash_softmax_regs': 184,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case06: b29cf18a6dc5483a; FULL search seed 2026210206.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'descending',
     'cute_flash_causal_loop_split': True,
     'cute_flash_causal_lpt_swizzle': 8,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 88,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 4,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 5,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 40,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4',
     'cute_flash_precompute_qk_desc': True,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'pre_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_stateful',
     'cute_flash_softmax_regs': 192,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
    # case10: ec9f8a9b85fcdd5d; FULL search seed 2026210210.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'descending',
     'cute_flash_causal_loop_split': True,
     'cute_flash_causal_lpt_swizzle': 8,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 72,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 0,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 3,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 40,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 12.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_stateful',
     'cute_flash_softmax_regs': 176,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 0,
     'cute_reduction_reloads': ['auto']},
    # case12: f77c17b1b03848e4; FULL search seed 2026210212.
    {'block_sizes': [1, 128, 128],
     'cute_collective_compute': 'warp',
     'cute_collective_copy': 'scalar',
     'cute_collective_mma': False,
     'cute_collective_native_seeded': False,
     'cute_collective_tmem_a': False,
     'cute_collective_tmem_seed': False,
     'cute_flash_causal_kv_order': 'descending',
     'cute_flash_causal_loop_split': True,
     'cute_flash_causal_lpt_swizzle': 8,
     'cute_flash_clc_heads_per_batch': 0,
     'cute_flash_clc_pdl': False,
     'cute_flash_clc_stages': 1,
     'cute_flash_corr_regs': 72,
     'cute_flash_corr_tile_size': 16,
     'cute_flash_disc_pipe': 1,
     'cute_flash_e2e_offset': 0,
     'cute_flash_e2e_offset0': 0,
     'cute_flash_e2e_schedule': 'xu',
     'cute_flash_epi_stg': False,
     'cute_flash_epi_stg_gmem': 'stage',
     'cute_flash_epi_stg_store': 'slice',
     'cute_flash_epi_tma': True,
     'cute_flash_epi_tma_setup': 'shared',
     'cute_flash_exp2_packet': '1x1',
     'cute_flash_first_load_order': 4,
     'cute_flash_kv_order': 'ascending',
     'cute_flash_kv_stage': 3,
     'cute_flash_kv_tile_n': 128,
     'cute_flash_masked_e2e_schedule': 'inherit',
     'cute_flash_mma_interleave': True,
     'cute_flash_other_regs': 32,
     'cute_flash_p_store_rep': 16,
     'cute_flash_packed_reduce': True,
     'cute_flash_persistent': False,
     'cute_flash_persistent_ctas_per_sm': 1,
     'cute_flash_persistent_loop': 'while',
     'cute_flash_pipeline_family': 'fa4',
     'cute_flash_precompute_qk_desc': False,
     'cute_flash_q_tile_count': 2,
     'cute_flash_recompute_tile_coords': False,
     'cute_flash_rescale_chunk_cols': 16,
     'cute_flash_rescale_threshold': 8.0,
     'cute_flash_role_chain': False,
     'cute_flash_role_map': 'helion',
     'cute_flash_row_sum_schedule': 'post_acquire',
     'cute_flash_rowmax': 'tmem',
     'cute_flash_s_load_rep': 32,
     'cute_flash_s_stage': 2,
     'cute_flash_skip_rescale_stats': False,
     'cute_flash_small_biased': True,
     'cute_flash_softmax_disc': False,
     'cute_flash_softmax_lowering': 'resident_stateful',
     'cute_flash_softmax_regs': 176,
     'cute_flash_softmax_setup': 'shared',
     'cute_flash_sp_row_sum': 'whole',
     'cute_flash_split_p_arrive': True,
     'cute_flash_stat_transport': 'single',
     'cute_flash_wait_hint': 10000000,
     'cute_reduction_reloads': ['auto']},
]


def key_attention_output(
    batch: int, heads: int, sequence: int, head_dim: int, dtype: str
) -> int:
    key = (batch, heads, sequence, head_dim, dtype)
    try:
        return _DENSE_KEYS.index(key)
    except ValueError:
        raise ValueError(f"No pretuned attention_output config for {key}") from None


def autotune_attention_output(
    batch: int, heads: int, sequence: int, head_dim: int, dtype: str
) -> dict:
    index = key_attention_output(batch, heads, sequence, head_dim, dtype)
    return deepcopy(_DENSE_CONFIGS[index])


def key_causal_attention_output(
    batch: int, heads: int, sequence: int, head_dim: int, dtype: str
) -> int:
    key = (batch, heads, sequence, head_dim, dtype)
    try:
        return _CAUSAL_KEYS.index(key)
    except ValueError:
        raise ValueError(f"No pretuned causal_attention_output config for {key}") from None


def autotune_causal_attention_output(
    batch: int, heads: int, sequence: int, head_dim: int, dtype: str
) -> dict:
    index = key_causal_attention_output(batch, heads, sequence, head_dim, dtype)
    return deepcopy(_CAUSAL_CONFIGS[index])
