"""
Shape-bucket heuristic for pretuned RoPE kernels on AMD MI350.

Generated from bf16 autotuning run:
  benchmarks/logs/rope_autotune_mi350_bf16_gpu1_20260513_111656

The config dictionaries use exact TritonBench (hidden_size, seq_length) buckets
and fall back to the H8192_T2048 config when a shape is not in the table.
"""

from __future__ import annotations


_DEFAULT_SHAPE = (8192, 2048)

_FWD_CONFIGS_BY_SHAPE = {(8192, 1024): {'block_sizes': [1, 1],
                'loop_orders': [[0, 1]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 1,
                'indexing': ['pointer',
                             'block_ptr',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'xyz',
                'waves_per_eu': 1,
                'matrix_instr_nonkdim': 0},
 (8192, 2048): {'block_sizes': [1, 1],
                'loop_orders': [[1, 0]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 3,
                'indexing': ['pointer',
                             'block_ptr',
                             'pointer',
                             'block_ptr',
                             'block_ptr',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 1,
                'matrix_instr_nonkdim': 0},
 (8192, 4096): {'block_sizes': [1, 1],
                'loop_orders': [[0, 1]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 8,
                'num_stages': 1,
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'block_ptr',
                             'pointer',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 1,
                'matrix_instr_nonkdim': 0},
 (8192, 8192): {'block_sizes': [1, 1],
                'loop_orders': [[0, 1]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 1,
                'indexing': ['pointer',
                             'pointer',
                             'block_ptr',
                             'pointer',
                             'pointer',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 2,
                'matrix_instr_nonkdim': 0},
 (8192, 16384): {'block_sizes': [1, 1],
                 'loop_orders': [[0, 1]],
                 'l2_groupings': [1],
                 'range_unroll_factors': [0],
                 'range_warp_specializes': [],
                 'range_num_stages': [0],
                 'range_multi_buffers': [None],
                 'range_flattens': [None],
                 'load_eviction_policies': ['', '', '', ''],
                 'num_warps': 8,
                 'num_stages': 1,
                 'indexing': ['pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer'],
                 'atomic_indexing': [],
                 'pid_type': 'flat',
                 'waves_per_eu': 1,
                 'matrix_instr_nonkdim': 0},
 (512, 2048): {'block_sizes': [1, 16],
               'loop_orders': [[1, 0]],
               'l2_groupings': [2],
               'range_unroll_factors': [0],
               'range_warp_specializes': [],
               'range_num_stages': [0],
               'range_multi_buffers': [None],
               'range_flattens': [None],
               'load_eviction_policies': ['', '', '', ''],
               'num_warps': 16,
               'num_stages': 4,
               'indexing': ['pointer',
                            'block_ptr',
                            'block_ptr',
                            'block_ptr',
                            'pointer',
                            'pointer'],
               'atomic_indexing': [],
               'pid_type': 'xyz',
               'waves_per_eu': 1,
               'matrix_instr_nonkdim': 16},
 (2048, 2048): {'block_sizes': [1, 16],
                'loop_orders': [[1, 0]],
                'l2_groupings': [16],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 8,
                'num_stages': 2,
                'indexing': ['block_ptr',
                             'block_ptr',
                             'pointer',
                             'block_ptr',
                             'pointer',
                             'block_ptr'],
                'atomic_indexing': [],
                'pid_type': 'xyz',
                'waves_per_eu': 1,
                'matrix_instr_nonkdim': 0}}

_BWD_CONFIGS_BY_SHAPE = {(8192, 1024): {'block_sizes': [1, 1],
                'loop_orders': [[0, 1]],
                'l2_groupings': [4],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 2,
                'num_stages': 2,
                'indexing': ['block_ptr',
                             'pointer',
                             'pointer',
                             'block_ptr',
                             'pointer',
                             'block_ptr'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 2,
                'matrix_instr_nonkdim': 0},
 (8192, 2048): {'block_sizes': [1, 1],
                'loop_orders': [[1, 0]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 2,
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'block_ptr',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 2,
                'matrix_instr_nonkdim': 0},
 (8192, 4096): {'block_sizes': [1, 1],
                'loop_orders': [[1, 0]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 1,
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'block_ptr'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 2,
                'matrix_instr_nonkdim': 0},
 (8192, 8192): {'block_sizes': [1, 1],
                'loop_orders': [[0, 1]],
                'l2_groupings': [1],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 1,
                'num_stages': 1,
                'indexing': ['pointer',
                             'block_ptr',
                             'pointer',
                             'pointer',
                             'block_ptr',
                             'pointer'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 2,
                'matrix_instr_nonkdim': 0},
 (8192, 16384): {'block_sizes': [1, 1],
                 'loop_orders': [[0, 1]],
                 'l2_groupings': [1],
                 'range_unroll_factors': [0],
                 'range_warp_specializes': [],
                 'range_num_stages': [0],
                 'range_multi_buffers': [None],
                 'range_flattens': [None],
                 'load_eviction_policies': ['', '', '', ''],
                 'num_warps': 2,
                 'num_stages': 1,
                 'indexing': ['pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'block_ptr',
                              'block_ptr'],
                 'atomic_indexing': [],
                 'pid_type': 'flat',
                 'waves_per_eu': 4,
                 'matrix_instr_nonkdim': 16},
 (512, 2048): {'block_sizes': [1, 16],
               'loop_orders': [[0, 1]],
               'l2_groupings': [1],
               'range_unroll_factors': [1],
               'range_warp_specializes': [],
               'range_num_stages': [2],
               'range_multi_buffers': [False],
               'range_flattens': [False],
               'load_eviction_policies': ['', '', '', ''],
               'num_warps': 8,
               'num_stages': 3,
               'indexing': ['block_ptr',
                            'block_ptr',
                            'pointer',
                            'pointer',
                            'pointer',
                            'pointer'],
               'atomic_indexing': [],
               'pid_type': 'persistent_blocked',
               'num_sm_multiplier': 1,
               'waves_per_eu': 1,
               'matrix_instr_nonkdim': 0},
 (2048, 2048): {'block_sizes': [1, 16],
                'loop_orders': [[1, 0]],
                'l2_groupings': [8],
                'range_unroll_factors': [0],
                'range_warp_specializes': [],
                'range_num_stages': [0],
                'range_multi_buffers': [None],
                'range_flattens': [None],
                'load_eviction_policies': ['', '', '', ''],
                'num_warps': 8,
                'num_stages': 4,
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'block_ptr',
                             'pointer',
                             'block_ptr'],
                'atomic_indexing': [],
                'pid_type': 'flat',
                'waves_per_eu': 1,
                'matrix_instr_nonkdim': 16}}


def autotune_rope_fwd(hidden_size: int, seq_length: int) -> dict[str, object]:
    assert isinstance(hidden_size, int)
    assert isinstance(seq_length, int)
    shape = (hidden_size, seq_length)
    if shape in _FWD_CONFIGS_BY_SHAPE:
        return _FWD_CONFIGS_BY_SHAPE[shape]
    return _FWD_CONFIGS_BY_SHAPE[_DEFAULT_SHAPE]


def autotune_rope_bwd(hidden_size: int, seq_length: int) -> dict[str, object]:
    assert isinstance(hidden_size, int)
    assert isinstance(seq_length, int)
    shape = (hidden_size, seq_length)
    if shape in _BWD_CONFIGS_BY_SHAPE:
        return _BWD_CONFIGS_BY_SHAPE[shape]
    return _BWD_CONFIGS_BY_SHAPE[_DEFAULT_SHAPE]
