name: Benchmark Dispatch

on:
  pull_request:

jobs:
  run-b200:
    uses: ./.github/workflows/benchmark.yml
    permissions:
      id-token: write
      contents: read
    with:
      runner: linux.dgx.b200
      python-version: "3.12"
      image: nvidia/cuda:12.9.1-devel-ubuntu24.04
      runtime-version: cu129
      container-options: --gpus all
      alias: b200
      max-runners: 12

  run-mi325x:
    uses: ./.github/workflows/benchmark.yml
    permissions:
      id-token: write
      contents: read
    with:
      runner: linux.rocm.gpu.gfx942.2
      python-version: "3.12"
      image: rocm/dev-ubuntu-24.04:7.0-complete
      runtime-version: rocm7.0
      container-options: --device=/dev/kfd --device=/dev/dri
      alias: mi325x
      max-runners: 6
