name: Benchmark Dispatch

on:
  pull_request:

jobs:
  gen-matrix-h100:
    uses: ./.github/workflows/_compute-matrix.yml
    with:
      max-runners: 12

  benchmark-h100:
    needs: gen-matrix-h100
    strategy:
      matrix: ${{ fromJSON(needs.gen-matrix-h100.outputs.matrix) }}
    uses: ./.github/workflows/benchmark.yml
    permissions:
      id-token: write
      contents: read
    with:
      runner: linux.aws.h100
      python-version: "3.12"
      image: nvidia/cuda:12.9.1-devel-ubuntu24.04
      runtime-version: cu129
      container-options: --gpus all
      alias: h100
      num-shards: ${{ matrix.num_shards }}
      shard: ${{ matrix.shard }}
  gen-matrix-b200:
    uses: ./.github/workflows/_compute-matrix.yml
    with:
      max-runners: 12

  benchmark-b200:
    needs: gen-matrix-b200
    strategy:
      matrix: ${{ fromJSON(needs.gen-matrix-b200.outputs.matrix) }}
    uses: ./.github/workflows/benchmark.yml
    permissions:
      id-token: write
      contents: read
    with:
      runner: linux.dgx.b200
      python-version: "3.12"
      image: nvidia/cuda:12.9.1-devel-ubuntu24.04
      runtime-version: cu129
      container-options: --gpus all
      alias: b200
      num-shards: ${{ matrix.num_shards }}
      shard: ${{ matrix.shard }}

  gen-matrix-mi325x:
    uses: ./.github/workflows/_compute-matrix.yml
    with:
      max-runners: 6

  benchmark-mi325x:
    needs: gen-matrix-mi325x
    uses: ./.github/workflows/benchmark.yml
    strategy:
      matrix: ${{ fromJSON(needs.gen-matrix-mi325x.outputs.matrix) }}
    permissions:
      id-token: write
      contents: read
    with:
      runner: linux.rocm.gpu.gfx942.2
      python-version: "3.12"
      image: rocm/dev-ubuntu-24.04:7.0-complete
      runtime-version: rocm7.0
      container-options: --device=/dev/kfd --device=/dev/dri
      alias: mi325x
      num-shards: ${{ matrix.num_shards }}
      shard: ${{ matrix.shard }}
