name: Benchmark Nightly

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at midnight PST (8 AM UTC)
  workflow_dispatch:

jobs:
  dispatch-benchmark:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Dispatch benchmark_dispatch workflow
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'benchmark_dispatch.yml',
              ref: 'main',
              inputs: {
                run_h100: 'true',
                run_b200: 'true',
                run_mi325x: 'true'
              }
            })
