name: Test Documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: torch27
          python-version: 3.12
          channels: defaults,pytorch,conda-forge

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.conda/pkgs
            ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('.github/workflows/docs-test.yml') }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: Install docs requirements and project
        run: |
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Build documentation
        run: |
          cd docs/
          make html
          make linkcheck

      - name: Upload built docs
        uses: actions/upload-artifact@v5
        with:
          name: docs-html
          path: site
