name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Create environment
        run: |
          uv venv --python ${{ matrix.python-version }}

      - name: Install PyTorch
        run: |
          source .venv/bin/activate
          uv pip install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu128

      - name: Install lint dependencies
        run: |
          source .venv/bin/activate
          uv pip install pyright
          uv pip install .'[dev]'

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files
